---

- hosts: all
  become: true
  tasks:

    - name: Install updates - CentOS
      yum:
        update_cache: yes
        update_only: yes
      when: ansible_distribution == "CentOS"
      tags: always

    - name: Install updates - Ubuntu 
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      tags: always

- name: This play tries to install apache and php packages
  hosts: web_servers
  become: true
  tasks:   

    - name: "Install apache and php package in Ubuntu servers"
      tags: "apache-php, ubuntu"
      apt:
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Debian","Ubuntu"] and ansible_distribution_version == "18.04"
        
    - name: "Install httpd and php package in CentOS servers"
      tags: "apache-php, centos"
      yum:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS" 

- hosts: db_servers
  become: yes
  tasks:

    - name: Install mariaDB (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when:  ansible_distribution == "Ubuntu"

    - name: Install mariaDB (CentOS)
      yum: 
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: yes
  tasks:
    - name: install samba file server on Ubuntu or CentOS
      package: 
        name: samba
        state: latest


    
