---

- hosts: all
  become: true
  tasks:

  - name: ping hosts - [test1]
    ping:
    tags: test1

  - name: ping hosts - [test2]
    ping:
    tags: test2

  - name: ping hosts - [always]
    ping:
    tags: always

  - name: ping hosts - [no tags]
    ping:
 