---

- hosts: all
  become: true
  tasks:

  - name: Gather facts
    gather_facts:

  - name: Install httpd 
    package:
      name: 
      - "{{ my_webserver }}"
      - "{{ my_php }}"
      update_cache: true
      state: latest
    #when: ansible_distribution == "CentOS" 

  - name: Start/stop httpd
    command: 
      cmd: systemctl start "{{ my_webserver }}"
    when: ansible_distribution_version == "7.8" or ansible_distribution == "CentOS" 
    #ansible.builtin.command: systemctl stop httpd

  - name: Set https port
    command:
      cmd: firewall-cmd --add-port=80/tcp
    when: ansible_distribution == "CentOS" 



