- name: "Install apache and php package in Ubuntu servers"
  tags: webserver
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: "Starts the httpd service in centos hosts"
  tags: "httpd,centos,webserver"
  service:
    name: "{{ apache_service_name }}"
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"

- name: "Opens port 80 in cent OS webserver"
  tags: "centos,webserver"
  command:
    cmd: firewall-cmd --add-port=80/tcp
  when: ansible_distribution == "CentOS" 

- name: "Play to update the httpd config file"
  tags: "httpd,centos,webserver"
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin someone@somewhere.in
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: This play copies the default HTML file
  tags: "apache-php,webserver"
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
